/*******************************************************************************
 * Copyright (C) 2013 NOAA/NCDC - Wendy Gross.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors:
 *     Wendy Gross
 *     Peter Brewer
 ******************************************************************************/


package org.fhaes.fhchart.gui;

import javax.swing.JPanel;
import javax.swing.JButton;
import java.awt.*;
import java.awt.event.*;


/**
 * Controls for a FHAES Plot
 */
public class ControlPanel extends JPanel
{
	public static final long serialVersionUID = 24362462L;

	// Actions that this class will generate ...
	private static final String VIEW_COMPOSITE_FILTERS = "viewCompositeFilters";
	private static final String EXPORT_PDF = "exportPDF";
	private static final String EXPORT_PNG = "exportPNG";
	private static final String UPDATE_CHART = "updateChartPanel";
	private static final String COMPOSITE = "composite";


	ActionListener myActionListener = null; // Object that will listen for and act on
											//   this objects button/Action events.
											//   In this case, one ActionListener is 
											//   listening for/acting on all button
											//   events generated by this object.
											// Note that this object does not know or care
											//   what this.myActionListener will do with the
											//   Button/Action events that will be generated
											//   when the user clicks the buttons.

	// GUI Components
	JPanel mainPanel = null; // top level panel that contains all controls.
	JButton zoomInitialBtn = null;
	JButton refreshBtn = null;

	// Wendy Continue here...
	JButton viewCompositeFiltersBtn = null;
	JButton exportPDFBtn = null;
	JButton exportPNGBtn = null;
	JButton updateChartBtn = null;
	JButton compositeBtn = null;


	/**
	 * Constructs a new FHXControlPanel.
	 *
	 * @param myActionListenerIn object that will be listening for my button events.
	 */
	public ControlPanel(ActionListener myActionListenerIn) {
		myActionListener = myActionListenerIn;
		createGUI();
	}

	/**
	 * Create the Graphical User Interface.
	 *
	 */
	private void createGUI()
	{
		mainPanel = new JPanel();
		mainPanel.setLayout(new GridLayout(1, 4));

		zoomInitialBtn = new JButton("Zoom Full Extent");
		zoomInitialBtn.addActionListener(myActionListener);
		zoomInitialBtn.setActionCommand("ZoomToFullExtent");
		mainPanel.add(zoomInitialBtn);

		viewCompositeFiltersBtn = new JButton("View Composite Axis Filters");
		viewCompositeFiltersBtn.addActionListener(myActionListener);
		viewCompositeFiltersBtn.setName(VIEW_COMPOSITE_FILTERS); // Object that listens for and handles events for this button
		//   will use the Name of the zoomInitialBtn object
		//   to know what action to take.
		//mainPanel.add(viewCompositeFiltersBtn);

		refreshBtn = new JButton("Fit Graph to Window Width");
		refreshBtn.addActionListener(myActionListener);
		refreshBtn.setActionCommand("ZoomToWidth");
		// Wendy todo 20080606	
		mainPanel.add(refreshBtn);


		exportPDFBtn = new JButton("Export PDF");
		exportPDFBtn.addActionListener(myActionListener);
		exportPDFBtn.setName(EXPORT_PDF); // this.myActionListener
		//   will use the Name of the exportPDFBtn object 
		//   to know what action to take.
		//mainPanel.add(exportPDFBtn);

		exportPNGBtn = new JButton("Export PNG");
		exportPNGBtn.addActionListener(myActionListener);
		exportPNGBtn.setName(EXPORT_PNG); // this.myActionListener
		//   will use the Name of the exportPNGBtn object 
		//   to know what action to take.
		//mainPanel.add(exportPNGBtn);

		updateChartBtn = new JButton("Update Chart");
		updateChartBtn.addActionListener(myActionListener);
		updateChartBtn.setName(UPDATE_CHART); // this.myActionListener
		//mainPanel.add(updateChartBtn);

		compositeBtn = new JButton("Comp");
		compositeBtn.addActionListener(myActionListener);
		compositeBtn.setName(COMPOSITE); // this.myActionListener
		//mainPanel.add(compositeBtn);


		this.add(mainPanel);
	}
}